export const EXERCISE_MUSCLE_GROUP = {
	CHEST: "CHEST",
	BACK: "BACK",
	SHOULDERS: "SHOULDERS",
	BICEPS: "BICEPS",
	TRICEPS: "TRICEPS",
	FOREARMS: "FOREARMS",
	CORE: "CORE",
	ABS: "ABS",
	QUADS: "QUADS",
	HAMSTRINGS: "HAMSTRINGS",
	CALVES: "CALVES",
	GLUTES: "GLUTES",
	NECK: "NECK",
	LOWER_BACK: "LOWER_BACK",
	UPPER_BACK: "UPPER_BACK",
	HIP_FLEXORS: "HIP_FLEXORS",
	OBLIQUES: "OBLIQUES",
	TRAPS: "TRAPS",
	DELTS: "DELTS",
} as const;

export type ExerciseMuscleGroup = keyof typeof EXERCISE_MUSCLE_GROUP;
