export const EXERCISE_MUSCLE_GROUP = {
	ABDOMINALS: "ABDOMINALS",
	ADDUCTORS: "ADDUCTORS",
	BICEPS: "BICEPS",
	CALVES: "CALVES",
	CHEST: "CHEST",
	FOREARMS: "FOREARMS",
	GLUTES: "GLUTES",
	HAMSTRINGS: "HAMSTRINGS",
	LATS: "LATS",
	LOWER_BACK: "LOWER BACK",
	MIDDLE_BACK: "MIDDLE BACK",
	NECK: "NECK",
	QUADRICEPS: "QUADRICEPS",
	SHOULDERS: "SHOULDERS",
	TRAPS: "TRAPS",
	TRICEPS: "TRICEPS",
	DELTS: "DELTS",
	HIP_FLEXORS: "HIP_FLEXORS",
	CORE: "CORE",
} as const;

export type ExerciseMuscleGroup = keyof typeof EXERCISE_MUSCLE_GROUP;
